### ISSUE TITLE
404 for whisper api

### ISSUE THREAD

**Issue by cian0** [SillyTavern/SillyTavern-Extras#177]
Browser mode works on Chrome but Whisper just goes 404:

127.0.0.1 - - [22/Oct/2023 18:43:47] "OPTIONS /api/speech-recognition/whisper/process-audio HTTP/1.1" 404 -

**Comment by prestonzen** [comment]
I also have the same issue. Everything was set up as per the instructions. I do have it enabled in --extensions 

![image](https://github.com/SillyTavern/SillyTavern-Extras/assets/36439263/b7717f4e-aa4c-4373-b6cd-8aacfe047543)

**Comment by cian0** [comment]
My extras looks like  this:
python server.py --enable-modules=coqui-tts,silero-tts,whisper-speech-recognition

**Comment by cian0** [comment]
Oh yeah it is working now thank you!
