### ISSUE TITLE
Error 500 RVC vocie not work

### ISSUE THREAD

**Issue by alastor367** [SillyTavern/SillyTavern-Extras#239]
_P.S. I used a translator to translate my problem from my language into English_

For some reason, when I try to use rvc it crashes in my console with such an error (given below) and on the same page error 500 does anyone know how to fix it? (I've checked the topic and even the topics with the same blend, nothing helped me from what I've seen)

> AttributeError: module 'ffmpeg' has no attribute 'input'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 210, in vc_single
>     audio = load_audio(input_audio_path, 16000)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 161, in load_audio
>     raise RuntimeError(f"Failed to load audio: {e}")
> RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'
> 
> 'NoneType' object has no attribute 'dtype'
> 2024-04-30 19:24:03 | INFO | werkzeug | 127.0.0.1 - - [30/Apr/2024 19:24:03] "POST /api/voice-conversion/rvc/process-audio HTTP/1.1" 500 -
> gin_channels: 256 self.spk_embed_dim: 109
> <All keys matched successfully>
> Traceback (most recent call last):
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 153, in load_audio
>     ffmpeg.input("pipe:0", threads=0)
>     ^^^^^^^^^^^^
> AttributeError: module 'ffmpeg' has no attribute 'input'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 210, in vc_single
>     audio = load_audio(input_audio_path, 16000)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 161, in load_audio
>     raise RuntimeError(f"Failed to load audio: {e}")
> RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'
> 
> 'NoneType' object has no attribute 'dtype'
> 2024-04-30 19:24:04 | INFO | werkzeug | 127.0.0.1 - - [30/Apr/2024 19:24:04] "POST /api/voice-conversion/rvc/process-audio HTTP/1.1" 500 -

**Comment by alastor367** [comment]
I forgot to add I'm using Windows 10

**Comment by alastor367** [comment]
I forgot to add I'm using Windows 10

**Comment by alastor367** [comment]
i miss click and close ;-; im dump

**Comment by Cohee1207** [comment]
Do you have ffmpeg available in PATH?

**Comment by alastor367** [comment]
> Do you have ffmpeg available in PATH?

yes
![image](https://github.com/SillyTavern/SillyTavern-Extras/assets/132879286/c1bdda21-e02d-4d04-9ac4-ed4dfb57b5db)

**Comment by alastor367** [comment]
> Do you have ffmpeg available in PATH?

I also have the version for Python installed. I also have everything from requirements.txt and requirements-rvc.txt

**Comment by alastor367** [comment]
GPU and CPU failed + windows path failed
