### ISSUE TITLE
Issue with built-in Extentions Installer

### ISSUE THREAD

**Issue by CactaeSan** [SillyTavern/SillyTavern-Extras#244]
Hello everyone. When trying to install extensions, like OBJECTIVES, HYPEBOT, CHAT TOP BAR etc, it fails and give me this error message:

Extension Installation Failed
Server Error: Error: spawn git
ENOENT at
ChidProcess._handle.onexit
(node:internal/child_process:286:19) at on ErrorNT
(node:internal/child_process:484:16) at process.processTicksAndRejections
(node:internal/process/task_queues:82:21)'

I do not understand at all what's it's all about, so I clueless on how to adress the issue. The only thing I could do, was to check again I had set a user ID and mail on GIT.

If there's a kind soul willing to help me, I'd be very grateful to it.
By the way, congratulations everyone, because ST is a very super tool !

**Comment by Cohee1207** [comment]
You need to have git installed on your machine. 

https://git-scm.com/downloads

**Comment by CactaeSan** [comment]
It is installed. Like I said in my post, I even check again and again that I had set a user ID and mail on GIT.
![Git](https://github.com/user-attachments/assets/f0b4d207-5da6-44f6-b4fa-0c6bc450768f)

**Comment by CactaeSan** [comment]
SOLVED. Thanx anyway to all the community !
