### ISSUE TITLE
Feature request: "Continue message"

### ISSUE THREAD

**Issue by Priestru** [SillyTavern/SillyTavern-extras#48]
Well, like it could be done ChatGPT or Ooba:

![image](https://github.com/SillyTavern/SillyTavern-extras/assets/108554892/6f1ffa73-8dd9-4155-a5a9-cd98e80b2bff)

Sometimes response isn't bad but too short, but you can't make model continue it. And also if you just send an empty message like in CAI it would respond with blank message. (Maybe it's trying to impersonate out of turn and getting nuked dunno)

**Comment by Woisek** [comment]
I would second that. Would be a nice feature.
